tabuada = int(input('Digite um número para gerar sua tabuada: '))
vezes0 = tabuada * 0
vezes1 = tabuada * 1
vezes2 = tabuada * 2
vezes3 = tabuada * 3
vezes4 = tabuada * 4
vezes5 = tabuada * 5
vezes6 = tabuada * 6
vezes7 = tabuada * 7
vezes8 = tabuada * 8
vezes9 = tabuada * 9
vezes10 = tabuada * 10
print('{} x 0 = {}'.format(tabuada, vezes0))
print('{} x 1 = {}'.format(tabuada, vezes1))
print('{} x 2 = {}'.format(tabuada, vezes2))
print('{} x 3 = {}'.format(tabuada, vezes3))
print('{} x 4 = {}'.format(tabuada, vezes4))
print('{} x 5 = {}'.format(tabuada, vezes5))
print('{} x 6 = {}'.format(tabuada, vezes6))
print('{} x 7 = {}'.format(tabuada, vezes7))
print('{} x 8 = {}'.format(tabuada, vezes8))
print('{} x 9 = {}'.format(tabuada, vezes9))
print('{} x 10 = {}'.format(tabuada, vezes10))
